name: Trigger Linting

on:
  push:
    branches:
      - development
  workflow_dispatch: true

jobs:
  trigger:
    uses: bcgov/des-git-workflows/.github/workflows/linting.yml@feature/add-linting-workflow